---
title: "Ops Dashboard - 2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(readxl)
library(tidyverse)
library(plotly)
library(ggmap)

remotes::install_github('rstudio/rmarkdown')

require(knitr)

# Read Excels Data
americas =read_excel("data/America Hiring File.xlsx",sheet = "data")
apac=read_excel("data/APAC Hiring File.xlsx",sheet = "data")
europe=read_excel("data/Europe Hiring File.xlsx",sheet = "data")

# New Object 
global=rbind(americas,apac,europe)

#Read file containing country coordinates
map=read_excel("data/Coordinate Map.xlsx")
```

Overview{data-icon="fa-globe"}
=============================
Row {data-width=150}
--------------------------------------
### New Hires
```{r}
newhires=global %>% filter(`Type of movement`=="Entry") %>% nrow()
valueBox(value = newhires,icon = "fa-user-plus",caption = "New Hires",color = "steelblue")
```

### Resign Number
```{r}
exits=global %>% filter(`Type of movement`=="Exit") %>% nrow()
valueBox(value = exits,icon = "fa-user-times",caption = "Exits", color = "orange")
```

### Exchange Net Employment
```{r}
newhires=global %>% filter(`Type of movement`=="Entry") %>% nrow()
exits=global %>% filter(`Type of movement`=="Exit") %>% nrow()

netchange=(newhires-exits)

# Data Vizualisation
if(netchange>0){
  valueBox(value = netchange,icon = "fa-arrow-up",caption = "Net Exchange", color = "forestgreen")
} else{
valueBox(value = netchange,icon = "fa-arrow-down",caption = "Net Exchange", color = "forestgreen")}

```

Row
----------------------------------

### Monthly Movement
```{r}
# Data Transformation
h1=global %>% group_by(Month,`Type of movement`) %>% 
  summarise(count=n())

# Data Visualization
p1=plot_ly(data = h1,
        x=h1$Month,
        y=h1$count) %>% 
  add_lines(linetype = h1$`Type of movement`,
            data = h1$count,
            hoverinfo="text",
            text=paste(h1$count)) %>% 
  layout(title='Employment Rate',
         xaxis=list(title="Month",
         yaxis=list(title="Total")))
p1
```

### Region Movement
```{r}
# Data Transformation
h2=global %>% 
  group_by(Month,`Type of movement`,Country) %>% 
  summarise(count=n())

#Add long/lat info based on country name from map
h2=left_join(h2,map[,2:4],by=c("Country"="name"))


# Data Visualization
p2=plot_geo(h2,locationmode="world") %>% 
  add_markers(x=h2$longitude,
              y=h2$latitude,
              size=h2$count,
              color=h2$`Type of movement`,
              hoverinfo="text",
              hovertext=paste(h2$`Type of movement`,": ",h2$count)) %>% 
  layout(title='Region Info')


p2

```

New hires {data-icon="fa-user-plus"}
==================
Row{data-height=250}
--------

### Avg Monthly Hire
```{r}
# Data Transformation
newhire_bymonth=global %>% 
  filter(`Type of movement`=="Entry") %>% 
  group_by(Month) %>% 
  summarise(count=n())

avgnewhire=round(mean(newhire_bymonth$count),2)
  
valueBox(avgnewhire,icon = "fa-user-plus",caption = "Average monthly new hires",color = "steelblue")
```

### Newbie Employment Type
```{r}
# Data Transformation
h5=global %>% 
  filter(`Type of movement`=="Entry") %>% 
  group_by(`Employment type`) %>% 
  summarise(count=n())

# Data Visualization
p5=plot_ly(h5) %>% 
  add_pie(labels=h5$`Employment type`,values=h5$count,hole=0.5) %>% 
  layout(title = "Employment Type")

p5
```

### Newbie Authorisation Type
```{r}
h6=global %>% 
  filter(`Type of movement`=="Entry") %>% 
  group_by(`Work Authorisation`) %>% 
  summarise(count=n())

p6=plot_ly(h6) %>% 
  add_pie(labels=h6$`Work Authorisation`,values=h6$count,hole=0.5) %>% 
  layout(title = "Authorisation Type")

p6
```

Row
----------

### Newbie Country Based
```{r}

#Summarise and group by Country
h3=global %>% 
  filter(`Type of movement`=="Entry") %>% 
  group_by(Month,Country) %>% 
  summarise(count=n())

#Use spread to make the table ready for plots
h3=spread(h3,key = Country,value = count)


#Bar chart by country
p3=plot_ly(h3,
           x=h3$Month,
           hoverinfo="text") %>% 
  add_bars(y=h3$Argentina,
           name="Argentina",
           hovertext=paste(h3$Argentina)) %>% 
  add_bars(y=h3$Australia,
           name="Australia",
           hovertext=paste("Australia: ",h3$Australia)) %>% 
  add_bars(y=h3$Brazil,
           name="Brazil",
           hovertext=paste("Brazil: ",h3$Brazil)) %>%
  add_bars(y=h3$Canada,
           name="Canada",
           hovertext=paste("Canada: ",h3$Canada)) %>%
  add_bars(y=h3$India,
           name="India",
           hovertext=paste("India: ",h3$India)) %>%
  add_bars(y=h3$Romania,
           name="Romania",
           hovertext=paste("Romania: ",h3$Romania)) %>%
  add_bars(y=h3$USA,
           name="USA",
           hovertext=paste("USA",h3$USA)) %>% 
  layout(title = "Country Based Hiring")
  
  
p3
```

### Newbie Organisation Source
```{r}
# Data Transformation
h4=global %>% 
  filter(`Type of movement`=="Entry") %>% 
  group_by(Month,Org) %>% 
  summarise(count=n())


h4=spread(h4,key = Org,value = count)

# Data Visualization
p4=plot_ly(data = h4,
           x=h4$Month,
           hoverinfo="text") %>% 
  add_bars(y=h4$Corporate,
           name="Corporate",
           hovertext=paste("Corporate: ",h4$Corporate)) %>% 
  add_bars(y=h4$Delivery,
           name="Delivery",
           hovertext=paste("Delivery: ",h4$Delivery)) %>% 
  add_bars(y=h4$DeliveryOps,
           name="DeliveryOps",
           hovertext=paste("DeliveryOps: ",h4$DeliveryOps)) %>% 
  add_bars(y=h4$Support,
           name="Support",
           hovertext=paste("Support: ",h4$Support)) %>% 
  layout(title = "Hiring Source")

p4
```

Attrition {data-icon="fa-user-times"}
====================

Row{data-height=250}
--------

### Monthly Attrition Rate
```{r}
# Data Transformation
attn_bymonth=global %>% 
  filter(`Type of movement`=="Exit") %>% 
  group_by(Month) %>% 
  summarise(count=n())

avgattn=round(mean(attn_bymonth$count),2)
  
valueBox(avgattn,icon = "fa-user-times",caption = "Average monthly attrition",color = "orange")
```

### Attrition by Position 
```{r}
# Data Transformation
h7=global %>% 
  filter(`Type of movement`=="Exit") %>% 
  group_by(`Employment type`) %>% 
  summarise(count=n())

p7=plot_ly(h7) %>% 
  add_pie(labels=h7$`Employment type`,values=h7$count,hole=0.5) %>% 
  layout(title = "Attrition by Position")

p7
```

### Attrition by Work Authorisation
```{r}
# Data Transformation
h8=global %>% 
  filter(`Type of movement`=="Exit") %>% 
  group_by(`Work Authorisation`) %>% 
  summarise(count=n())

# Data Visulatization
p8=plot_ly(h8) %>% 
  add_pie(labels=h8$`Work Authorisation`,values=h8$count,hole=0.6) %>% 
  layout(title = "Attrition by Work Authorization")

p8

```

Row
----------

### Attrition by Country
```{r}

#Summarise and group by Country
h9=global %>% 
  filter(`Type of movement`=="Exit") %>% 
  group_by(Month,Country) %>% 
  summarise(count=n())

#Use spread to make the table ready for plots
h9=spread(h9,key = Country,value = count)

# Visualization
p9=plot_ly(h9,
           x=h9$Month,
           hoverinfo="text") %>% 
  add_bars(y=h9$Australia,
           name="Australia",
           hovertext=paste("Australia: ",h9$Australia)) %>% 
  add_bars(y=h9$India,
           name="India",
           hovertext=paste("India: ",h9$India)) %>%
  add_bars(y=h9$Romania,
           name="Romania",
           hovertext=paste("Romania: ",h9$Romania)) %>%
  add_bars(y=h9$USA,
           name="USA",
           hovertext=paste("USA",h9$USA)) %>% 
  layout(title = "Attrition by Country")

p9
```

### Attrition by Organisation
```{r}
#Create a summary grouped by Org
h10=global %>% 
  filter(`Type of movement`=="Exit") %>% 
  group_by(Month,Org) %>% 
  summarise(count=n())

#Make the table plot-ready
h10=spread(h10,key = Org,value = count)

# Visualization
p10=plot_ly(data = h10,
           x=h10$Month,
           hoverinfo="text") %>% 
  add_bars(y=h10$Corporate,
           name="Corporate",
           hovertext=paste("Corporate: ",h10$Corporate)) %>% 
  add_bars(y=h10$Delivery,
           name="Delivery",
           hovertext=paste("Delivery: ",h10$Delivery)) %>% 
  add_bars(y=h10$DeliveryOps,
           name="DeliveryOps",
           hovertext=paste("DeliveryOps: ",h10$DeliveryOps)) %>% 
  add_bars(y=h10$Support,
           name="Support",
           hovertext=paste("Support: ",h10$Support)) %>% 
  layout(title = "Attritiion by Organization")
p10
```


